functional:
 - Пользователь должен иметь возможность искать товары по ключевому слову или категории
 - Пользователь должен иметь возможность фильтровать товары
 - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
 - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
 - Пользователь должен иметь возможность переключить язык интерфейса
 - Сайт должен иметь локализацию (перевод) на русский и английский языки
non-functional:
 - айт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт должен иметь мобильную версию
 - Сайт нужно протестировать на совместимость с последними версиями браузеров
 - Сайт должен обрабатывать большое количество трафика
 - Сайт должен быть доступен на различных устройствах
implicit:
 - Пользователь должен видеть надпись/уведомление об успешном добавлении товара в корзину
 - Пользователь должен иметь возможность добавить нужное количество товаров в корзину, путем ручного ввода 
 - Пользователь должен иметь возможность видеть номера страниц товаров
 - Пользователь должен иметь возможность выбирать детали оформления заказа
 - Фильтры/категории/производитель должны быть в алфавитном порядке
 - Пользователь должен иметь возможность выбрать нужный размер товара
 - Пользователь не должен иметь возможность добавлять большее количество товаром, чем есть в наличии
 - Пользователь не должен иметь возможность вводить отрицательные значения цены и количества товаров
