functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - На странице товара должны отображаться название, рейтинг, цена со скидкой и без скидки
  - На странице каталога должны отображаться название, цена со скидкой и без скидки
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса (Русский/Английский)
  - Пользователь может, находясь на странице товара или в каталоге, добавить товар в корзину и продолжить выбирать товары в каталоге
  - Пользователь на странице корзины может удалить товар из корзины
  - Пользователь на странице корзины может продолжить выбирать товары в каталоге
  - Пользователь на странице корзины может оформить заказ с переходом на страницу оплаты
  - Корзина должна храниться в сессии браузера

non-functional:
  - Сайт должен быть разработан с учетом удобства использования (юзабилити)
  - Сайт должен быть оптимизирован для скорости работы (производительность)
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь адаптивную верстку для удобного просмотра на мобильных устройствах (адаптивность)
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров (кроссбраузерность)
  - Сайт должен быть способен обрабатывать большое количество трафика (масштабируемость)
  - Сайт должен быть доступен на различных устройствах (кроссплатформенность)

implicit:
  - Пользователь должен видеть надпись/уведомление об успешном добавлении товара в корзину (user feedback)
  - Пользователь должен иметь возможность добавить нужное количество товаров в корзину, используя ручной ввод или элементы управления (количество)
  - Пользователь должен видеть номера страниц при постраничном выводе товаров (пагинация)
  - Пользователь должен иметь возможность выбирать детали оформления заказа (доставка, адрес и т.п.) (оформление заказа)
  - Фильтры/категории/производители должны быть отсортированы (например, в алфавитном порядке) (сортировка)
  - Пользователь должен иметь возможность выбрать нужный размер товара (если применимо) (размер)
  - Пользователь не должен иметь возможность добавлять в корзину большее количество товара, чем есть в наличии на складе (ограничение количества)
  - Пользователь не должен иметь возможность вводить отрицательные значения цены и количества товаров (валидация данных)
  - Каталог товаров должен поддерживать постраничный вывод (пагинация)
  - Должна быть возможность увидеть общую сумму заказа в корзине.
  - Должна быть возможность увидеть количество товаров в корзине.
